"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
if __name__ == "__main__":
	
    x = 1
    y = 2
    n = 0
    sum = 2
    while n < 4000000 :
        n = x + y
        #L.append( n )
        x = y
        y = n
        #print(n, end = ' ')
        if n%2 == 0:
            sum = sum+n
    print(sum)
    #print(L)